### ISSUE TITLE
CWD not set correctly?

### ISSUE THREAD

**Issue by abliss** [realgud/realgud-trepan-ni#2]
if I invoke `realgud:trepan-ni`, the resulting `trepan-ni` subprocess seems to always get the CWD of `~/.dotfiles`, the location of my `.emacs` file where `(require 'realgud-trepan-ni)` was evaluated.  This results in the script being debugged failing spuriously when performing relative-path operations (like `require('fs').readFileSync('../foo')` ... though not, strangely, when doing `require('../bar')`.) I can verify this by typing `process.cwd()` in the interactive `trepan-ni` prompt.

I would expect that the CWD of the `trepan-ni` process to be taken from the default directory of the buffer that I had open when I execute `M-x realgud:trepan-ni`.

**Comment by rocky** [comment]
I am not sure the mechanism is as you describe, although I believe you when you say you get certain results.

So let me try to break things down into how I believe this all works. 

First, let's remove `realgud-trepan-ni` from the equation. When you run `trepan-ni` the directory where you ran `trepan-ni` becomes the current working directory: 

```console
$ cd /tmp
$ trepan-ni /tmp/testing/gcd.js
< Debugger listening on ws://127.0.0.1:9229/e2c86dd9-9baf-4bb7-9029-a6d491ea6e8a
< For help see https://nodejs.org/en/docs/inspector
connecting to 127.0.0.1:9229 ... ok
(trepan-ni) < Debugger attached.
(trepan-ni) Break on start in testing/gcd.js:1
 -> 1 (function (exports, require, module, __filename, __dirname) { //!/usr/bin/env node
    2 var util = require("util");
    3 require("console");
(trepan-ni) process.cwd()
'/tmp'
(trepan-ni) quit
trepan-ni: That's all, folks!
$ cd testing 
$ trepan-ni /tmp/testing/gcd.js
< Debugger listening on ws://127.0.0.1:9229/5b7624ab-48c8-4258-9f78-0c4b21826e0a
< For help see https://nodejs.org/en/docs/inspector
connecting to 127.0.0.1:9229 ... ok
(trepan-ni) < Debugger attached.
(trepan-ni) Break on start in gcd.js:1
 -> 1 (function (exports, require, module, __filename, __dirname) { //!/usr/bin/env node
    2 var util = require("util");
    3 require("console");
(trepan-ni) process.cwd()
'/tmp/testing'
(trepan-ni) quit
$ 
```

Ok. Now with that let's add back in *realgud*. The thing here is that the code isn't doing anything special, it is using GNU Emacs' default behavior when creating or reusing process buffers. 

So that means that whatever directory was the current directory when you issued say `M-x realgud-trepan-ni` will be the current directory of the process buffer. And so there is no confusion (and to make it easier to report this kind of stuff when you create issues) it is printed at the top of the buffer. 

So I think if you edit the top level nodejs script that you want to debug and then run `M-x trepan-ni` you will find the `process.cwd()` will show the directory where the nodejs program resides. But that is no different than if you were to run it from a shell. 

If this is indeed true (and I make a lot of misakes which is why I write debuggers), I don't think this is a bug so much as your not making the connection between what happens in a shell versus inside GNU Emacs.

There is however a slight detail to pay attention to that is a little bit different. I find I am often running the debugger on a given program over and over again. Even though `trepan-ni` has a `run` command to restart the program, invariably the program exits and I want to run the program/debugger again using `M-x trepan-ni`. As a result, rather than create fresh new buffers for each invocation, `realgud` uses the last one if there is one. That makes it easier to look at past history: maybe there were breakpoints or special aliases that were used that I may need to reissue. 

When a buffer is reused, it keeps the current working directory of what it had before. There are occasions where that's not what you want: in particular, if the working directory wasn't set right the last time. 

When that happens, the simplest thing to do is to delete the process/command  buffer that has the wrong working directory and start again. There's probably an elisp function that will change the working directory if that's what you'd prefer to do instead. 

So if you are still reading this far, we come to the most important question: what could be done to reduce confusion in the future? (I would prefer not to have to explain this more than once if this is indeed the situation you encounter.)

As mentioned above, I do list the current working directory in the process/command buffer. It feels to me that there might be an option in `trepan-ni` analogous the the `-C` option on some other commands like `make` and `tar` which change the directory to whatever you specify. 

If you feel strongly about that, since trepan-ni is just nodejs, would you add that and put in a PR in the [trepan-ni](https://github.com/rocky/trepan-ni) project? 

The other thing I'd appreciate help on is taking the above and putting it a wiki somewhere. It could be in this Wiki or in the main realgud Wiki, since this doesn't seem to be realgud-trepan-ni specific.
 
 What do you think?
